#!/bin/sh
# Startup Info Script - Menampilkan informasi login

echo ""
echo "=========================================="
echo "   ☁️  CLOUD STORAGE 2.0 - STARTED"
echo "=========================================="
echo ""
echo "📌 ADMIN LOGIN"
echo "   URL:      http://localhost:5000/admin"
echo "   Username: admin"
echo "   Password: admin123"
echo ""
echo "📌 DATABASE (PostgreSQL)"
echo "   Host:     localhost:5432"
echo "   Database: clouddb"
echo "   Username: clouduserdb"
echo "   Password: cloudpassdb_secure2026"
echo ""
echo "   Connect:  docker exec -it cloud-storage2-postgres-1 psql -U clouduserdb -d clouddb"
echo ""
echo "📌 MinIO OBJECT STORAGE"
echo "   Console:  http://localhost:9001"
echo "   Endpoint: localhost:9000"
echo "   Username: adminminio"
echo "   Password: MinioSecret2026!"
echo "   Bucket:   cloud-storage"
echo ""
echo "📌 FRONTEND"
echo "   URL:      http://localhost:5000"
echo ""
echo "📌 API"
echo "   URL:      http://localhost:8080"
echo "   Health:   http://localhost:8080/health"
echo ""
echo "=========================================="
echo ""
